In [14]:
import numpy as np

# Stastical Operations

In [12]:
x = [i for i in range(0, 20, 2)]
y = [i for i in range(0, 30, 3)]

In [17]:
arr = np.array([x, y])
arr

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27]])

In [18]:
arr.min()

0

In [19]:
arr.max()

27

In [20]:
arr.std()

7.660776723022281

In [21]:
arr.mean()

11.25

In [22]:
arr.squeeze()

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27]])

In [23]:
arr.cumsum()

array([  0,   2,   6,  12,  20,  30,  42,  56,  72,  90,  90,  93,  99,
       108, 120, 135, 153, 174, 198, 225])

In [24]:
arr.flatten()

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18,  0,  3,  6,  9, 12, 15, 18,
       21, 24, 27])

# sequence, repetitions, and random numbers

In [31]:
np.linspace(0, 50, 10)

array([ 0.        ,  5.55555556, 11.11111111, 16.66666667, 22.22222222,
       27.77777778, 33.33333333, 38.88888889, 44.44444444, 50.        ])

In [34]:
np.logspace(2, 50, 10)

array([1.00000000e+02, 2.15443469e+07, 4.64158883e+12, 1.00000000e+18,
       2.15443469e+23, 4.64158883e+28, 1.00000000e+34, 2.15443469e+39,
       4.64158883e+44, 1.00000000e+50])