In [2]:
import numpy as np

# Stastical Operations

In [12]:
x = [i for i in range(0, 20, 2)]
y = [i for i in range(0, 30, 3)]

In [17]:
arr = np.array([x, y])
arr

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27]])

In [18]:
arr.min()

0

In [19]:
arr.max()

27

In [20]:
arr.std()

7.660776723022281

In [21]:
arr.mean()

11.25

In [22]:
arr.squeeze()

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27]])

In [23]:
arr.cumsum()

array([  0,   2,   6,  12,  20,  30,  42,  56,  72,  90,  90,  93,  99,
       108, 120, 135, 153, 174, 198, 225])

In [24]:
arr.flatten()

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18,  0,  3,  6,  9, 12, 15, 18,
       21, 24, 27])

# sequence, repetitions, and random numbers

In [31]:
np.linspace(0, 50, 10)

array([ 0.        ,  5.55555556, 11.11111111, 16.66666667, 22.22222222,
       27.77777778, 33.33333333, 38.88888889, 44.44444444, 50.        ])

In [34]:
np.logspace(2, 50, 10)

array([1.00000000e+02, 2.15443469e+07, 4.64158883e+12, 1.00000000e+18,
       2.15443469e+23, 4.64158883e+28, 1.00000000e+34, 2.15443469e+39,
       4.64158883e+44, 1.00000000e+50])

# Part 2

In [3]:
arr = np.array([8, 10, 12, 14, 18, 20])

In [5]:
arr10 = np.where(arr > 10)
arr10

(array([2, 3, 4, 5]),)

In [6]:
arr[arr10]

array([12, 14, 18, 20])

In [8]:
np.where(arr>10, 'oh no', 'Great')

array(['Great', 'Great', 'oh no', 'oh no', 'oh no', 'oh no'], dtype='<U5')

# read and write csv file

In [10]:
url = 'https://raw.githubusercontent.com/selva86/datasets/master/Auto.csv'
data = np.genfromtxt(url, delimiter= ',', skip_header= 1, 
              filling_values= -1000, dtype = 'float')

In [12]:
data.shape

(392, 9)

In [13]:
np.savetxt('data.csv', data, delimiter=',')

In [32]:
np.save('data.npy', data)

In [26]:
np.savez('data.npz', data)

In [35]:
d = np.load('data.npy')
d

array([[   18.,     8.,   307., ...,    70.,     1., -1000.],
       [   15.,     8.,   350., ...,    70.,     1., -1000.],
       [   18.,     8.,   318., ...,    70.,     1., -1000.],
       ...,
       [   32.,     4.,   135., ...,    82.,     1., -1000.],
       [   28.,     4.,   120., ...,    82.,     1., -1000.],
       [   31.,     4.,   119., ...,    82.,     1., -1000.]])

In [36]:
d.shape

(392, 9)

In [37]:
d2 = np.load('data.npz')

In [38]:
d2.files

['arr_0']

In [39]:
d3 = d2['arr_0']

In [40]:
d3.shape

(392, 9)

# concat with row and col wise

In [42]:
arr1 = np.zeros([4, 4])
arr2 = np.ones([4, 4])

In [43]:
arr1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [44]:
arr2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# For concat 3 methods available
- concatenate
- vstack for column wise
- hstack for row wise
- r_ for column wise
- c_ for row wise

In [45]:
np.concatenate([arr1, arr2], axis = 0)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [46]:
np.vstack([arr1, arr2])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [49]:
np.r_[arr1, arr2]

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# Concat axis wise

In [48]:
np.concatenate([arr1, arr2], axis = 1)

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

In [50]:
np.concatenate([arr1, arr2], axis = 0)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# sort a numpy array

In [51]:
arr = np.random.randint(1, 10, size = [10, 5])
arr

array([[7, 2, 4, 8, 3],
       [4, 9, 7, 8, 6],
       [4, 1, 8, 5, 6],
       [8, 2, 7, 2, 1],
       [9, 9, 5, 8, 4],
       [1, 1, 7, 5, 6],
       [3, 8, 5, 9, 2],
       [4, 4, 7, 7, 8],
       [5, 7, 4, 7, 7],
       [7, 6, 4, 8, 7]])

In [52]:
np.sort(arr, axis = 0)

array([[1, 1, 4, 2, 1],
       [3, 1, 4, 5, 2],
       [4, 2, 4, 5, 3],
       [4, 2, 5, 7, 4],
       [4, 4, 5, 7, 6],
       [5, 6, 7, 8, 6],
       [7, 7, 7, 8, 6],
       [7, 8, 7, 8, 7],
       [8, 9, 7, 8, 7],
       [9, 9, 8, 9, 8]])

In [53]:
np.sort(arr, axis=1)

array([[2, 3, 4, 7, 8],
       [4, 6, 7, 8, 9],
       [1, 4, 5, 6, 8],
       [1, 2, 2, 7, 8],
       [4, 5, 8, 9, 9],
       [1, 1, 5, 6, 7],
       [2, 3, 5, 8, 9],
       [4, 4, 7, 7, 8],
       [4, 5, 7, 7, 7],
       [4, 6, 7, 7, 8]])

# working with dates

In [54]:
d = np.datetime64('2019-06-02 23:10:00')

In [57]:
d + 1000

numpy.datetime64('2019-06-02T23:26:40')

In [59]:
dates = np.arange(np.datetime64('2019-06-02'), np.datetime64('2020-06-02'), 2)
dates[:5]

array(['2019-06-02', '2019-06-04', '2019-06-06', '2019-06-08',
       '2019-06-10'], dtype='datetime64[D]')

<function datetime64.clip>

# Numpy Advanced Function

In [64]:
def foo(x):
    if x % 2 == 1:
        return x ** 2
    else:
        return x / 2 

In [65]:
foo(12)

6.0

In [67]:
arr

array([[7, 2, 4, 8, 3],
       [4, 9, 7, 8, 6],
       [4, 1, 8, 5, 6],
       [8, 2, 7, 2, 1],
       [9, 9, 5, 8, 4],
       [1, 1, 7, 5, 6],
       [3, 8, 5, 9, 2],
       [4, 4, 7, 7, 8],
       [5, 7, 4, 7, 7],
       [7, 6, 4, 8, 7]])

In [69]:
v = np.vectorize(foo, otypes=['float'])

In [71]:
v(10)

array(5.)

In [72]:
v(arr)

array([[49.,  1.,  2.,  4.,  9.],
       [ 2., 81., 49.,  4.,  3.],
       [ 2.,  1.,  4., 25.,  3.],
       [ 4.,  1., 49.,  1.,  1.],
       [81., 81., 25.,  4.,  2.],
       [ 1.,  1., 49., 25.,  3.],
       [ 9.,  4., 25., 81.,  1.],
       [ 2.,  2., 49., 49.,  4.],
       [25., 49.,  2., 49., 49.],
       [49.,  3.,  2.,  4., 49.]])

49